PACKAGE_NAME="gigamate_acpi"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="gigamate_acpi"
DEST_MODULE_LOCATION[0]="/kernel/extra/gigamate_acpi"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=${kernel_source_dir}"
